# Generated by Django 3.0.6 on 2020-05-25 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 14, 3, 20, 555681, tzinfo=utc)),
        ),
    ]
